language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml ./tests
  - ./vendor/bin/phpcs src

after_script:
  - php vendor/bin/coveralls -v
